title: Guojiao An 安国娇's Homepage
page-top-title: Guojiao An | TAGMA
top-section-bg-text: Be what you wanna be ！
home-subtitle: Guojiao An&ensp;|&ensp;安国娇
copyright-text: '&copy; TAGMA Group 2026-2028. All Rights Reserved.'
permissions:
  contents: read
  pages: write
  id-token: write   # 这个极其重要，用于生成 OIDC 令牌
